### PR TITLE
Fix two small issues

### PR DESCRIPTION
**Pull request by stoecker**

### CODE REVIEW

**Comment by stoecker** [comment]
I have no idea why this includes the 5 changes already in this repo.

**Comment by perlpunk** [comment]
Thanks!
Can you rebase to current master? I think that's why those other commits appear.

**Comment by stoecker** [comment]
Cool I added another bunch of useless crap. I appreciate that git can do a lot, but it's awful that it's so complicated for the simplest tasks.

**Comment by stoecker** [comment]
Well, half an hour work for that. AAAAAAAAAAAAAAAAAAAaarrrrrrrrrrrrrghhhh.

**Comment by stoecker** [comment]
META.yml probably needs some more tuning. I remember that I had to install a bunch of stuff not mentioned there :)

**Pull request merged**
