### PR TITLE
makecmd - handle alike to perl and rm

### PR DESCRIPTION
**Pull request by stoecker**

### CODE REVIEW

**Comment by coolo** [comment]
Sorry - I'm surely not a role model when it comes to writing commit logs - but 'makecmd' is even for me too vague. Your PR summary is already good enough, so please amend and force push

**Comment by stoecker** [comment]
On Wed, 7 Nov 2018, Stephan Kulow wrote:

> Sorry - I'm surely not a role model when it comes to writing commit logs 
> - but 'makecmd' is even for me too vague. Your PR summary is already 
> good enough, so please amend and force push

Well, now I have three useless merge commits and I have no idea how to 
get rid of these.

Ciao
-- 
http://www.dstoecker.eu/ (PGP key available)

**Comment by coolo** [comment]
git rebase -i and then replace possible 'pick' in all but the first line with f

**Comment by coolo** [comment]
git rebase -i origin/master (if you have origin point here as I have :)

**Comment by coolo** [comment]
don't worry - I just remembered github can squash PRs

**Comment by stoecker** [comment]
> don't worry - I just remembered github can squash PRs

How?

**Comment by coolo** [comment]
it's an option on merging

**Pull request merged**
